name: midnight_confession_game
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_generative_ai: ^0.4.0

  # YENİ: Oyuncu profilini kaydetmek için bu paketi ekliyoruz.
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cases/
